from enum import Enum


class GameStates(Enum):
    PLAYERS_TURN = 1
    ENEMY_TURN = 2
    PLAYER_DEAD = 3
    SHOW_INVENTORY = 4
    DROP_INVENTORY = 5
    TARGETING = 6
    LEVEL_UP = 7
    MAGIC_LEVEL_UP = 8
    CHARACTER_SCREEN = 9
    BODY_SCREEN = 10
    HELP_SCREEN = 11
    CASTING_SPELL = 12
    READ_SCROLL = 13
